version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/app/fullstack-youtube/client
      - /usr/app/fullstack-youtube/client/node_modules
    ports:
      - '5234:5234'
    # networks:
    #   - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/app/fullstack-youtube/backend
      - /usr/app/fullstack-youtube/backend/node_modules
    ports:
      - '4444:4444'
    depends_on:
      - redis_cache
      - db
    # networks:
    #   - my_network
      
  db:
    ports:
      - '27017:27017'
    image: mongo

  redis_cache:
    ports:
      - '6379:6379'
    # container_name: redis
    image: redis
    
    # networks:
    #   - my_network
  
# networks:
#   my_network:
#     driver: bridge